### ISSUE TITLE
Não está encontrando os apps

### ISSUE THREAD

**Issue by hashdefault** [thiagopena/djangoSIGE#126]
**$ python3 manage.py migrate**      

Traceback (most recent call last):
  File "/home/gabriel-bueno/.local/lib/python3.10/site-packages/django/apps/config.py", line 244, in create
    app_module = import_module(app_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'base'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gabriel-bueno/Projects/python/djangoSIGE/manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/home/gabriel-bueno/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/gabriel-bueno/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/home/gabriel-bueno/.local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/gabriel-bueno/.local/lib/python3.10/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/home/gabriel-bueno/.local/lib/python3.10/site-packages/django/apps/config.py", line 246, in create
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Cannot import 'base'. Check that 'djangosige.apps.base.apps.BaseConfig.name' is correct.

---

Este é o primeiro dos apps instalados e ele reclama o erro acima. Alguém ja passou por isso ?

**Comment by solvercpv** [comment]
olá vai ter que fazer em todos as pastas dentro de djangosige/apps/ e alterar o apps.py:
class BaseConfig(AppConfig):
    name = 'base' alterar para name = 'djangosige.apps.base'

**Comment by hashdefault** [comment]
Correto, obrigado.
