### ISSUE TITLE
Deploy no Heroku com erro

### ISSUE THREAD

**Issue by devmaster100** [thiagopena/djangoSIGE#52]
Estou tentando fazer deploy em uma conta grátis, para poder usar no navegador, online, quando quiser, porém estou recebendo o seguinte erro.

Traceback (most recent call last):
  File "manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/__init__.py", line 317, in execute
    settings.INSTALLED_APPS
  File "/app/.heroku/python/lib/python3.6/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/app/.heroku/python/lib/python3.6/site-packages/django/conf/__init__.py", line 43, in _setup
    self._wrapped = Settings(settings_module)
  File "/app/.heroku/python/lib/python3.6/site-packages/django/conf/__init__.py", line 106, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/app/.heroku/python/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/djangosige/configs/__init__.py", line 3, in <module>
    from .settings import *
  File "/app/djangosige/configs/settings.py", line 4, in <module>
    from .configs import DEFAULT_DATABASE_URL, DEFAULT_FROM_EMAIL, EMAIL_HOST, EMAIL_HOST_USER, EMAIL_HOST_PASSWORD, EMAIL_PORT, EMAIL_USE_TLS
ModuleNotFoundError: No module named 'djangosige.configs.configs'

O que pode ser? Existe uma hospedagem grátis melhor que o heroku para esse projeto?

**Comment by brunomaffei** [comment]
Estou tendo o mesmo erro!
conseguiu achar o motivo? 
vlw

**Comment by carlos-moreno** [comment]
@devmaster100 e @brunomaffei conseguiram resolver o problema no heroku, tive acesso a aplicação esses dias buscando ajudar o @jasonrosa92 e subimos a aplicação com sucesso no heroku.

Fazendo uma busca rápida no código, realmente não existe um módulo com o nome 'djangosige.configs.configs', qualquer coisa tenta um git pull para atualizar o projeto.

**Comment by lucasitz** [comment]
Nao consigo dar deploy no heroku.. da erro no geraldo qdo tenta instalar la.. os amigos que conseguirem poderiam disponibilizar como foi feito ?

**Comment by andrecamara** [comment]
@lucasitz , eu consegui fazer o deploy no heroku, e está instalando as dependencias sem problemas. Não fiz nenhuma mudança drástica no requirements.txt:

> django>=2.1.9
dj-database-url==0.5.*
python-decouple==3.1
pytz==2018.3
reportlab==3.4.*
six==1.11.*
cryptography>=2.3
lxml==4.2.*
pyOpenSSL==17.5.*
signxml==2.5.*
psycopg2==2.8.4
gunicorn==20.0.4
whitenoise==5.0.1
requests==2.22.0
https://github.com/thiagopena/geraldo/archive/master.zip
https://github.com/thiagopena/PySIGNFe/archive/master.zip

Meu maior problema no heroku tem sido setar o locale para pt_BR (tive que fazer as conversões de moeda processando as strings mesmo. Alguém conseguiu resolver isso?

**Comment by lucasitz** [comment]
vc pode mostrar como ta seu procfile ? nao to acertando o meu

**Comment by andrecamara** [comment]
Olá @lucasitz ,
O meu Procfile está assim:

`web: gunicorn djangosige.wsgi --log-file=-`

Lembrando que o nome do arquivo **Procfile** deve iniciar com P maiúsculo (case sensitive).
Abs

**Comment by jasonrosa92** [comment]
oi @lucasitz você deve deixar o geraldo assim no requirements:

https://github.com/thiagopena/geraldo/archive/master.zip
e excluir o outro que é baixado automaticante.

deve ir no settings.py que está assim =  from .settings import *
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default=[], cast=Csv())

no default você deve deixar ele assim = default="*"

**Comment by silveira-alfredo** [comment]
Verifiquem se o arquivo existe: **djangosige/configs/configs.py**
Ele esta no **.gitignore** por isso nao sobe utilizando git
