### ISSUE TITLE
Não consigo instalar

### ISSUE THREAD

**Issue by dayvidallan** [thiagopena/djangoSIGE#77]
Bom dia Professor tudo bem?

Eu sou novo em programação e estou tendo um problema na hora de instalar, sempre dar essa mensagem:

$ pip install -r requirements.txt
ERROR: Exception:
Traceback (most recent call last):
  File "c:\users\user\djangosige\.venv\lib\site-packages\pip\_internal\cli\base_command.py", line 153, in _main
    status = self.run(options, args)
  File "c:\users\user\djangosige\.venv\lib\site-packages\pip\_internal\commands\install.py", line 362, in run
    wheel_cache
  File "c:\users\user\djangosige\.venv\lib\site-packages\pip\_internal\cli\req_command.py", line 258, in populate_requirement_set
    use_pep517=options.use_pep517):
  File "c:\users\user\djangosige\.venv\lib\site-packages\pip\_internal\req\req_file.py", line 117, in parse_requirements
    for req in req_iter:
  File "c:\users\user\djangosige\.venv\lib\site-packages\pip\_internal\req\req_file.py", line 178, in process_line
    shlex.split(options_str), defaults)  # type: ignore
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\shlex.py", line 306, in split
    return list(lex)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\shlex.py", line 296, in __next__
    token = self.get_token()
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\shlex.py", line 105, in get_token
    raw = self.read_token()
TypeError: 'NoneType' object is not callable

Você poderia me ajudar a saber como resolvo isso?

**Comment by thiagopena** [comment]
Boa noite @dayvidallan , estranho, não conheço esse erro, conseguiu resolver?

**Comment by dayvidallan** [comment]
Bom dia,

Já tentei de tudo, mas não consigo, não sei se é pq estou usando o Python mais novo.
________________________________
De: Thiago Pena <notifications@github.com>
Enviado: sexta-feira, 8 de novembro de 2019 20:46
Para: thiagopena/djangoSIGE <djangoSIGE@noreply.github.com>
Cc: dayvidallan <dayvidallan@hotmail.com>; Mention <mention@noreply.github.com>
Assunto: Re: [thiagopena/djangoSIGE] Não consigo instalar (#77)


Boa noite @dayvidallan<https://github.com/dayvidallan> , estranho, não conheço esse erro, conseguiu resolver?

**Comment by rafaelrbnet** [comment]
Eu consegui instalando as dependências uma a uma na mão.
Meu python é o 3.7

Em seg, 11 de nov de 2019 10:37, dayvidallan <notifications@github.com>
escreveu:

**Comment by dayvidallan** [comment]
Fiz isso também, mas continuou com o mesmo erro. Não sei se é pq programo no windows.
________________________________
De: Rafael Baena Neto <notifications@github.com>
Enviado: segunda-feira, 11 de novembro de 2019 11:32
Para: thiagopena/djangoSIGE <djangoSIGE@noreply.github.com>
Cc: dayvidallan <dayvidallan@hotmail.com>; Mention <mention@noreply.github.com>
Assunto: Re: [thiagopena/djangoSIGE] Não consigo instalar (#77)

Eu consegui instalando as dependências uma a uma na mão.
Meu python é o 3.7

Em seg, 11 de nov de 2019 10:37, dayvidallan <notifications@github.com>
escreveu:

**Comment by victtorvpb** [comment]
@dayvidallan você usa o windows 10?

**Comment by dayvidallan** [comment]
Sim, o windows 10 pro

________________________________
De: Victor Pereira <notifications@github.com>
Enviado: terça-feira, 12 de novembro de 2019 09:06
Para: thiagopena/djangoSIGE <djangoSIGE@noreply.github.com>
Cc: dayvidallan <dayvidallan@hotmail.com>; Mention <mention@noreply.github.com>
Assunto: Re: [thiagopena/djangoSIGE] Não consigo instalar (#77)


@dayvidallan<https://github.com/dayvidallan> você usa o windows 10?

**Comment by rafaelrbnet** [comment]
E ai.

Tenta uma coisa
Abre o arquivo requirements.txt
Executa o pip install de cada componente sem a versão. Pois assim ele vai
pegar a última estável

Em ter, 12 de nov de 2019 09:44, dayvidallan <notifications@github.com>
escreveu:

**Comment by leojoker** [comment]
Entra no requeriments.txt e adiciona o sinal de >= 
Vai instalar sem problemas

**Comment by rg3915** [comment]
O erro descrito (parser do shlex quebrando no pip install -r) é típico de versões antigas de pip + Python 3.7 no Windows. O processo de instalação foi modernizado usando uv (https://docs.astral.sh/uv/), que isola a versão do Python e instala as dependências de forma reprodutível, eliminando esse tipo de erro:


```
git clone https://github.com/thiagopena/djangoSIGE.git
cd djangoSIGE
uv sync
```
